export const API_ENDPOINT_KEYS = {
  LOGIN: "/login",
  REGISTER: "/registration",
  VERIFY: "/account/verify",
  POST: "/post",
  ACTIVE_ACCOUNT: "/account/active",
  UPLOAD_IMAGE: "/attachments",
  RENEW_TOKEN: "/refresh-token",
  CREATE_POST: "/post",
  GET_PROFILE: "/profile",
  FOLLOWER: "/follower",
  FOLLOWING: "/following",
  RESEND: "/account/verification_token",
  FORGOT: "/account/password",
  CHECK: "/account/check",
  ATTACTMENT: "/attachment",
  CHANGE_AVATAR: "/profile/avatar",
  LIKE: "/like",
  COMMENT: "/comment",
  NEWFEED: "/newsfeed",
  ACCOUNT_REPORT: "/accountReport",
  POST_REPORT: "/postReport",
  COMMENT_REPORT: "/commentReport",
};
